### ISSUE TITLE
NamePlate/ Text Vibrates

### ISSUE THREAD

**Issue by TheArtGun** [yoship1639/ValheimVRM#13] opened 2021-09-17 21:35 UTC
The gif is too big for posting so here is a link:
[https://gyazo.com/2a622ea69c75d72dc2b1ff0fc0f2c4ec](url)
This happens with all VRMs but not the default game model. I've tried scaling up, scaling down, adjusting the camera auto adjust (true/false) and Y offset but nothing helps. 

The vibration speed is influenced by the location of the camera, behind and in front of the model is worst and at the sides it slows down but never fully stops.

**Comment by linthiel** [comment] 2021-09-18 01:21
I am also experiencing this issue, this issue seems to be related to the latest update as I did not notice this prior to hearth and home. Granted I played solo so I didn't use chat often.

**Comment by Scifeur** [comment] 2021-09-18 01:28
Supposedly another mod called BetterUI fixes this issue so you can use that as a temporary fix until the mod author figures this out. I hope this helps you both! If you need a link to the mod then please let me know!

**Comment by linthiel** [comment] 2021-09-18 02:22
I can confirm that betterui does not resolve the issue for me.

**Comment by madetofall** [comment] 2021-09-18 02:24
BetterUI just hides the problem by disabling the part that jitters, it doesn't fix anything.

If you can tolerate lower frame rates, capping the framerate on the game below 40 seems to stop the jitter, though.

**Comment by linthiel** [comment] 2021-09-18 05:04
> 
> 
> BetterUI just hides the problem by disabling the part that jitters, it doesn't fix anything.
> 
> If you can tolerate lower frame rates, capping the framerate on the game below 40 seems to stop the jitter, though.

Confirmed a frame cap of 39 solves the jittering.

**Comment by linthiel** [comment] 2021-09-18 16:53
Just noticed that artgun's gif isn't viewable, here is a demonstration of the issue from ironmouses stream last night. https://clips.twitch.tv/DullCooperativeCurlewWOOP-usvg8bqKpThLevlf

**Comment by Scifeur** [comment] 2021-09-19 01:37
> The gif is too big for posting so here is a link:
> [https://gyazo.com/2a622ea69c75d72dc2b1ff0fc0f2c4ec](url)
> This happens with all VRMs but not the default game model. I've tried scaling up, scaling down, adjusting the camera auto adjust (true/false) and Y offset but nothing helps.
> 
> The vibration speed is influenced by the location of the camera, behind and in front of the model is worst and at the sides it slows down but never fully stops.

Sorry to ask but are you able to confirm that your "settings_player.txt" file located in your steam's ValheimVRM folder is changed to match your vrm model's name to a perfect T and is this mod is the only one you had on when you noticed this issue?

**Comment by yoship1639** [comment] 2021-09-22 19:39
This issue has been fixed in ver. 1.0.13.
* Fixed an issue where the text displayed above the player's head would vibrate.

こちらの問題はver1.0.13で修正しました。
* プレイヤーの頭上に表示されるテキストが振動する問題を修正

**Closed by yoship1639** 2021-09-22 19:39 UTC
